import type { FormulaItem } from "@/data/formulaData";

// Generated by tools/formula-importer/export-drafts-to-formula-data.js.
// Do not edit manually; approve drafts and rerun the exporter instead.
export const importedFormulaData: FormulaItem[] = [
  {
    "chapter": "函数",
    "commonMistakes": [
      "待人工补充易错点。"
    ],
    "example": "待人工补充示例题。",
    "id": "mineru-d54de01afd64",
    "imported": true,
    "keywords": [
      "g \\left( x \\right) 公式",
      "函数"
    ],
    "latex": "g \\left( x \\right) = \\log _ { a } x + \\log _ { a } \\left( 2 - x \\right)",
    "name": "g \\left( x \\right) 公式",
    "scenario": "的图象如图所示，则函数",
    "source": "mineru",
    "sourceFile": "mineru-output/test/auto/test_content_list_v2.json",
    "steps": [
      "识别题目中的已知量和未知量。",
      "选择并代入公式。",
      "检查单位、符号和结果。"
    ],
    "subject": "math",
    "variables": [
      {
        "symbol": "g",
        "meaning": "待人工补充"
      },
      {
        "symbol": "x",
        "meaning": "待人工补充"
      },
      {
        "symbol": "l",
        "meaning": "待人工补充"
      },
      {
        "symbol": "o",
        "meaning": "待人工补充"
      },
      {
        "symbol": "a",
        "meaning": "待人工补充"
      }
    ]
  }
];
