import type { FormulaItem } from "@/data/formulaData";

// Generated by tools/formula-importer/export-drafts-to-formula-data.js.
// Do not edit manually; approve drafts and rerun the exporter instead.
export const importedFormulaData: FormulaItem[] = [
  {
    "chapter": "函数",
    "commonMistakes": [
      "待人工补充易错点。"
    ],
    "example": "待人工补充示例题。",
    "id": "mineru-91b52d407bdd",
    "imported": true,
    "keywords": [
      "y 公式",
      "函数"
    ],
    "latex": "y = x ^ { \\frac { 1 } { 2 } }",
    "name": "y 公式",
    "scenario": "，y=1，x=1将平面直角坐标系的第一象限分成八个“卦限”：①，②，③，④，⑤，⑥，⑦，⑧(如图所示)．那么幂函数",
    "source": "mineru",
    "sourceFile": "mineru-output/test/auto/test_content_list_v2.json",
    "steps": [
      "识别题目中的已知量和未知量。",
      "选择并代入公式。",
      "检查单位、符号和结果。"
    ],
    "subject": "math",
    "variables": [
      {
        "symbol": "y",
        "meaning": "待人工补充"
      },
      {
        "symbol": "x",
        "meaning": "待人工补充"
      }
    ]
  },
  {
    "chapter": "函数",
    "commonMistakes": [
      "待人工补充易错点。"
    ],
    "example": "待人工补充示例题。",
    "id": "mineru-11fdcd33f99e",
    "imported": true,
    "keywords": [
      "x 公式",
      "函数"
    ],
    "latex": "x = \\frac { 1 } { 2 }",
    "name": "x 公式",
    "scenario": "equation_inline",
    "source": "mineru",
    "sourceFile": "mineru-output/test/auto/test_content_list_v2.json",
    "steps": [
      "识别题目中的已知量和未知量。",
      "选择并代入公式。",
      "检查单位、符号和结果。"
    ],
    "subject": "math",
    "variables": [
      {
        "symbol": "x",
        "meaning": "待人工补充"
      }
    ]
  },
  {
    "chapter": "函数",
    "commonMistakes": [
      "待人工补充易错点。"
    ],
    "example": "待人工补充示例题。",
    "id": "mineru-2f7deb53a927",
    "imported": true,
    "keywords": [
      "f \\left( x \\right) 公式",
      "函数"
    ],
    "latex": "f \\left( x \\right) = x ^ { a } , x \\in \\left( 0 , + \\infty \\right)",
    "name": "f \\left( x \\right) 公式",
    "scenario": "equation_inline",
    "source": "mineru",
    "sourceFile": "mineru-output/test/auto/test_content_list_v2.json",
    "steps": [
      "识别题目中的已知量和未知量。",
      "选择并代入公式。",
      "检查单位、符号和结果。"
    ],
    "subject": "math",
    "variables": [
      {
        "symbol": "f",
        "meaning": "待人工补充"
      },
      {
        "symbol": "x",
        "meaning": "待人工补充"
      },
      {
        "symbol": "a",
        "meaning": "待人工补充"
      },
      {
        "symbol": "i",
        "meaning": "待人工补充"
      },
      {
        "symbol": "n",
        "meaning": "待人工补充"
      },
      {
        "symbol": "t",
        "meaning": "待人工补充"
      },
      {
        "symbol": "y",
        "meaning": "待人工补充"
      }
    ]
  },
  {
    "chapter": "函数",
    "commonMistakes": [
      "待人工补充易错点。"
    ],
    "example": "待人工补充示例题。",
    "id": "mineru-d54de01afd64",
    "imported": true,
    "keywords": [
      "g \\left( x \\right) 公式",
      "函数"
    ],
    "latex": "g \\left( x \\right) = \\log _ { a } x + \\log _ { a } \\left( 2 - x \\right)",
    "name": "g \\left( x \\right) 公式",
    "scenario": "的图象如图所示，则函数",
    "source": "mineru",
    "sourceFile": "mineru-output/test/auto/test_content_list_v2.json",
    "steps": [
      "识别题目中的已知量和未知量。",
      "选择并代入公式。",
      "检查单位、符号和结果。"
    ],
    "subject": "math",
    "variables": [
      {
        "symbol": "g",
        "meaning": "待人工补充"
      },
      {
        "symbol": "x",
        "meaning": "待人工补充"
      },
      {
        "symbol": "l",
        "meaning": "待人工补充"
      },
      {
        "symbol": "o",
        "meaning": "待人工补充"
      },
      {
        "symbol": "a",
        "meaning": "待人工补充"
      }
    ]
  }
];
